// This file is generated by running the atlas_builder.
package game

/*
Note: This file assumes the existence of a type Rect that defines a rectangle in the same package, it can defined as:

	Rect :: rl.Rectangle

or if you don't use raylib:

	Rect :: struct {
		x, y, width, height: f32,
	}

or if you want to use integers (or any other numeric type):

	Rect :: struct {
		x, y, width, height: int,
	}

Just make sure you have something along those lines the same package as this file.
*/

TEXTURE_ATLAS_FILENAME :: "assets/atlas.png"
ATLAS_FONT_SIZE :: 32
LETTERS_IN_FONT :: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890?!&.,_:[]-+"

// A generated square in the atlas you can use with rl.SetShapesTexture to make
// raylib shapes such as rl.DrawRectangleRec() use the atlas.
SHAPES_TEXTURE_RECT :: Rect {157, 150, 10, 10}

Texture_Name :: enum {
	None,
	Cargo,
	Visible,
	Flag_No,
	Undo,
	Target,
	Reset,
	Duck,
	Move,
	Invisible,
	Flag_Ok,
	Wall,
	Chain,
}

Atlas_Texture :: struct {
	rect: Rect,
	// These offsets tell you how much space there is between the rect and the edge of the original document.
	// The atlas is tightly packed, so empty pixels are removed. This can be especially apparent in animations where
	// frames can have different offsets due to different amount of empty pixels around the frames.
	// In many cases you need to add {offset_left, offset_top} to your position. But if you are
	// flipping a texture, then you might need offset_bottom or offset_right.
	offset_top: f32,
	offset_right: f32,
	offset_bottom: f32,
	offset_left: f32,
	document_size: [2]f32,
	duration: f32,
}

atlas_textures: [Texture_Name]Atlas_Texture = {
	.None = {},
	.Cargo = { rect = {121, 0, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Visible = { rect = {186, 0, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Flag_No = { rect = {251, 0, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Undo = { rect = {316, 0, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Target = { rect = {381, 0, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Reset = { rect = {446, 0, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Duck = { rect = {121, 65, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Move = { rect = {0, 0, 120, 100}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {120, 100}, duration = 0.000},
	.Invisible = { rect = {186, 65, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Flag_Ok = { rect = {251, 65, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Wall = { rect = {316, 65, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Chain = { rect = {381, 65, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
}

Animation_Name :: enum {
	None,
}

Tag_Loop_Dir :: enum {
	Forward,
	Reverse,
	Ping_Pong,
	Ping_Pong_Reverse,
}

// Any aseprite file with frames will create new animations. Also, any tags
// within the aseprite file will make that that into a separate animation.
Atlas_Animation :: struct {
	first_frame: Texture_Name,
	last_frame: Texture_Name,
	document_size: [2]f32,
	loop_direction: Tag_Loop_Dir,
	repeat: u16,
}

atlas_animations := [Animation_Name]Atlas_Animation {
	.None = {},
}

Atlas_Glyph :: struct {
	rect: Rect,
	value: rune,
	offset_x: int,
	offset_y: int,
	advance_x: int,
}

atlas_glyphs: []Atlas_Glyph = {
	{ rect = {447, 91, 13, 18}, value = 'A', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {19, 102, 13, 18}, value = 'B', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {34, 102, 13, 18}, value = 'C', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {49, 102, 13, 18}, value = 'D', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {64, 102, 13, 18}, value = 'E', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {79, 102, 13, 18}, value = 'F', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {94, 102, 13, 18}, value = 'G', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {480, 106, 13, 18}, value = 'H', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {406, 131, 9, 18}, value = 'I', offset_x = 1, offset_y = 7, advance_x = 10},
	{ rect = {495, 106, 13, 18}, value = 'J', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {462, 108, 13, 18}, value = 'K', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {447, 111, 13, 18}, value = 'L', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {484, 66, 18, 18}, value = 'M', offset_x = 1, offset_y = 7, advance_x = 20},
	{ rect = {1, 122, 13, 18}, value = 'N', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {16, 122, 13, 18}, value = 'O', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {31, 122, 13, 18}, value = 'P', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {447, 66, 13, 23}, value = 'Q', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {46, 122, 13, 18}, value = 'R', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {61, 122, 13, 18}, value = 'S', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {76, 122, 13, 18}, value = 'T', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {91, 122, 13, 18}, value = 'U', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {106, 122, 13, 18}, value = 'V', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {484, 86, 18, 18}, value = 'W', offset_x = 1, offset_y = 7, advance_x = 20},
	{ rect = {477, 126, 13, 18}, value = 'X', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {492, 126, 13, 18}, value = 'Y', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {462, 128, 13, 18}, value = 'Z', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {21, 142, 16, 13}, value = 'a', offset_x = 1, offset_y = 12, advance_x = 18},
	{ rect = {121, 131, 13, 18}, value = 'b', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {55, 142, 13, 13}, value = 'c', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {136, 131, 13, 18}, value = 'd', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {70, 142, 13, 13}, value = 'e', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {151, 131, 13, 18}, value = 'f', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {166, 131, 13, 18}, value = 'g', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {181, 131, 13, 18}, value = 'h', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {507, 126, 4, 18}, value = 'i', offset_x = 1, offset_y = 7, advance_x = 5},
	{ rect = {145, 151, 11, 13}, value = 'j', offset_x = 1, offset_y = 12, advance_x = 13},
	{ rect = {196, 131, 13, 18}, value = 'k', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {428, 131, 4, 18}, value = 'l', offset_x = 1, offset_y = 7, advance_x = 5},
	{ rect = {440, 131, 18, 13}, value = 'm', offset_x = 1, offset_y = 12, advance_x = 20},
	{ rect = {85, 142, 13, 13}, value = 'n', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {100, 142, 13, 13}, value = 'o', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {211, 131, 13, 18}, value = 'p', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {226, 131, 13, 18}, value = 'q', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {440, 146, 13, 13}, value = 'r', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {477, 146, 13, 13}, value = 's', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {462, 88, 16, 18}, value = 't', offset_x = 1, offset_y = 7, advance_x = 18},
	{ rect = {492, 146, 13, 13}, value = 'u', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {455, 148, 13, 13}, value = 'v', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {1, 142, 18, 13}, value = 'w', offset_x = 1, offset_y = 12, advance_x = 20},
	{ rect = {115, 151, 13, 13}, value = 'x', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {241, 131, 13, 18}, value = 'y', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {130, 151, 13, 13}, value = 'z', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {417, 131, 9, 18}, value = '1', offset_x = 1, offset_y = 7, advance_x = 10},
	{ rect = {256, 131, 13, 18}, value = '2', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {271, 131, 13, 18}, value = '3', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {286, 131, 13, 18}, value = '4', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {301, 131, 13, 18}, value = '5', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {316, 131, 13, 18}, value = '6', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {331, 131, 13, 18}, value = '7', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {346, 131, 13, 18}, value = '8', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {361, 131, 13, 18}, value = '9', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {376, 131, 13, 18}, value = '0', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {391, 131, 13, 18}, value = '?', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {434, 131, 4, 18}, value = '!', offset_x = 1, offset_y = 7, advance_x = 5},
	{ rect = {1, 102, 16, 18}, value = '&', offset_x = 1, offset_y = 7, advance_x = 18},
	{ rect = {192, 151, 4, 3}, value = '.', offset_x = 1, offset_y = 21, advance_x = 5},
	{ rect = {470, 148, 5, 6}, value = ',', offset_x = 1, offset_y = 21, advance_x = 7},
	{ rect = {180, 151, 10, 3}, value = '_', offset_x = 1, offset_y = 21, advance_x = 11},
	{ rect = {507, 146, 4, 8}, value = ':', offset_x = 1, offset_y = 14, advance_x = 5},
	{ rect = {462, 66, 9, 20}, value = '[', offset_x = 1, offset_y = 6, advance_x = 9},
	{ rect = {473, 66, 9, 20}, value = ']', offset_x = 0, offset_y = 6, advance_x = 9},
	{ rect = {169, 151, 9, 4}, value = '-', offset_x = 0, offset_y = 15, advance_x = 8},
	{ rect = {39, 142, 14, 13}, value = '+', offset_x = 1, offset_y = 9, advance_x = 16},
}
