// This file is generated by running the atlas_builder.
package game

/*
Note: This file assumes the existence of a type Rect that defines a rectangle in the same package, it can defined as:

	Rect :: rl.Rectangle

or if you don't use raylib:

	Rect :: struct {
		x, y, width, height: f32,
	}

or if you want to use integers (or any other numeric type):

	Rect :: struct {
		x, y, width, height: int,
	}

Just make sure you have something along those lines the same package as this file.
*/

TEXTURE_ATLAS_FILENAME :: "assets/atlas.png"
ATLAS_FONT_SIZE :: 32
LETTERS_IN_FONT :: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890?!&.,_:[]-+"

// A generated square in the atlas you can use with rl.SetShapesTexture to make
// raylib shapes such as rl.DrawRectangleRec() use the atlas.
SHAPES_TEXTURE_RECT :: Rect {391, 150, 10, 10}

Texture_Name :: enum {
	None,
	Cargo,
	Visible,
	Flag_No,
	Target,
	Undo,
	Invisible,
	Reset,
	Duck,
	Move,
	Wall,
	Flag_Ok,
	Chain,
	Wormhole,
}

Atlas_Texture :: struct {
	rect: Rect,
	// These offsets tell you how much space there is between the rect and the edge of the original document.
	// The atlas is tightly packed, so empty pixels are removed. This can be especially apparent in animations where
	// frames can have different offsets due to different amount of empty pixels around the frames.
	// In many cases you need to add {offset_left, offset_top} to your position. But if you are
	// flipping a texture, then you might need offset_bottom or offset_right.
	offset_top: f32,
	offset_right: f32,
	offset_bottom: f32,
	offset_left: f32,
	document_size: [2]f32,
	duration: f32,
}

atlas_textures: [Texture_Name]Atlas_Texture = {
	.None = {},
	.Cargo = { rect = {121, 0, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Visible = { rect = {186, 0, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Flag_No = { rect = {251, 0, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Target = { rect = {316, 0, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Undo = { rect = {381, 0, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Invisible = { rect = {446, 0, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Reset = { rect = {121, 65, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Duck = { rect = {186, 65, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Move = { rect = {0, 0, 120, 100}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {120, 100}, duration = 0.000},
	.Wall = { rect = {251, 65, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Flag_Ok = { rect = {316, 65, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Chain = { rect = {381, 65, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
	.Wormhole = { rect = {446, 65, 64, 64}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {64, 64}, duration = 0.000},
}

Animation_Name :: enum {
	None,
}

Tag_Loop_Dir :: enum {
	Forward,
	Reverse,
	Ping_Pong,
	Ping_Pong_Reverse,
}

// Any aseprite file with frames will create new animations. Also, any tags
// within the aseprite file will make that that into a separate animation.
Atlas_Animation :: struct {
	first_frame: Texture_Name,
	last_frame: Texture_Name,
	document_size: [2]f32,
	loop_direction: Tag_Loop_Dir,
	repeat: u16,
}

atlas_animations := [Animation_Name]Atlas_Animation {
	.None = {},
}

Atlas_Glyph :: struct {
	rect: Rect,
	value: rune,
	offset_x: int,
	offset_y: int,
	advance_x: int,
}

atlas_glyphs: []Atlas_Glyph = {
	{ rect = {38, 122, 13, 18}, value = 'A', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {53, 122, 13, 18}, value = 'B', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {68, 122, 13, 18}, value = 'C', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {83, 122, 13, 18}, value = 'D', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {98, 122, 13, 18}, value = 'E', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {16, 124, 13, 18}, value = 'F', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {1, 127, 13, 18}, value = 'G', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {113, 131, 13, 18}, value = 'H', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {121, 151, 9, 18}, value = 'I', offset_x = 1, offset_y = 7, advance_x = 10},
	{ rect = {128, 131, 13, 18}, value = 'J', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {143, 131, 13, 18}, value = 'K', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {158, 131, 13, 18}, value = 'L', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {38, 102, 18, 18}, value = 'M', offset_x = 1, offset_y = 7, advance_x = 20},
	{ rect = {173, 131, 13, 18}, value = 'N', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {188, 131, 13, 18}, value = 'O', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {203, 131, 13, 18}, value = 'P', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {1, 102, 13, 23}, value = 'Q', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {218, 131, 13, 18}, value = 'R', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {233, 131, 13, 18}, value = 'S', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {248, 131, 13, 18}, value = 'T', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {263, 131, 13, 18}, value = 'U', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {278, 131, 13, 18}, value = 'V', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {58, 102, 18, 18}, value = 'W', offset_x = 1, offset_y = 7, advance_x = 20},
	{ rect = {293, 131, 13, 18}, value = 'X', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {308, 131, 13, 18}, value = 'Y', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {323, 131, 13, 18}, value = 'Z', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {195, 151, 16, 13}, value = 'a', offset_x = 1, offset_y = 12, advance_x = 18},
	{ rect = {338, 131, 13, 18}, value = 'b', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {229, 151, 13, 13}, value = 'c', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {353, 131, 13, 18}, value = 'd', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {244, 151, 13, 13}, value = 'e', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {368, 131, 13, 18}, value = 'f', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {383, 131, 13, 18}, value = 'g', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {398, 131, 13, 18}, value = 'h', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {503, 131, 4, 18}, value = 'i', offset_x = 1, offset_y = 7, advance_x = 5},
	{ rect = {379, 151, 11, 13}, value = 'j', offset_x = 1, offset_y = 12, advance_x = 13},
	{ rect = {413, 131, 13, 18}, value = 'k', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {143, 151, 4, 18}, value = 'l', offset_x = 1, offset_y = 7, advance_x = 5},
	{ rect = {155, 151, 18, 13}, value = 'm', offset_x = 1, offset_y = 12, advance_x = 20},
	{ rect = {259, 151, 13, 13}, value = 'n', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {274, 151, 13, 13}, value = 'o', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {428, 131, 13, 18}, value = 'p', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {443, 131, 13, 18}, value = 'q', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {289, 151, 13, 13}, value = 'r', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {304, 151, 13, 13}, value = 's', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {78, 102, 16, 18}, value = 't', offset_x = 1, offset_y = 7, advance_x = 18},
	{ rect = {319, 151, 13, 13}, value = 'u', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {334, 151, 13, 13}, value = 'v', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {175, 151, 18, 13}, value = 'w', offset_x = 1, offset_y = 12, advance_x = 20},
	{ rect = {349, 151, 13, 13}, value = 'x', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {458, 131, 13, 18}, value = 'y', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {364, 151, 13, 13}, value = 'z', offset_x = 1, offset_y = 12, advance_x = 15},
	{ rect = {132, 151, 9, 18}, value = '1', offset_x = 1, offset_y = 7, advance_x = 10},
	{ rect = {473, 131, 13, 18}, value = '2', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {488, 131, 13, 18}, value = '3', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {31, 142, 13, 18}, value = '4', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {46, 142, 13, 18}, value = '5', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {61, 142, 13, 18}, value = '6', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {76, 142, 13, 18}, value = '7', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {91, 142, 13, 18}, value = '8', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {16, 144, 13, 18}, value = '9', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {1, 147, 13, 18}, value = '0', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {106, 151, 13, 18}, value = '?', offset_x = 1, offset_y = 7, advance_x = 15},
	{ rect = {149, 151, 4, 18}, value = '!', offset_x = 1, offset_y = 7, advance_x = 5},
	{ rect = {96, 102, 16, 18}, value = '&', offset_x = 1, offset_y = 7, advance_x = 18},
	{ rect = {439, 151, 4, 3}, value = '.', offset_x = 1, offset_y = 21, advance_x = 5},
	{ rect = {409, 151, 5, 6}, value = ',', offset_x = 1, offset_y = 21, advance_x = 7},
	{ rect = {427, 151, 10, 3}, value = '_', offset_x = 1, offset_y = 21, advance_x = 11},
	{ rect = {403, 151, 4, 8}, value = ':', offset_x = 1, offset_y = 14, advance_x = 5},
	{ rect = {16, 102, 9, 20}, value = '[', offset_x = 1, offset_y = 6, advance_x = 9},
	{ rect = {27, 102, 9, 20}, value = ']', offset_x = 0, offset_y = 6, advance_x = 9},
	{ rect = {416, 151, 9, 4}, value = '-', offset_x = 0, offset_y = 15, advance_x = 8},
	{ rect = {213, 151, 14, 13}, value = '+', offset_x = 1, offset_y = 9, advance_x = 16},
}
